= Design of solution
:experimental:
:nofooter:
:source-highlighter: highlightjs
:stem:
:toc:
:xrefstyle: short

[[web_server_design]]
== Web Server design

The following diagram shows the design for the concurrent web server, using two fake clients to show how requests will be responded for both Prime Factorization and Goldbach Sums web apps. Note that inheritances involving added relevant classes are attached in the surroundings of the process diagram.

[#web_server_diagram]
.Web server diagram
image::web_server_12_design.svg[algin="center"]

== Web server production line

=== HttpConnectionHandler (Assembler)

**Role**: Initial assembler and entry point for incoming HTTP requests.

**Functionality**:

- Accepts connections from clients.
- Ask applications to parses the `HttpRequest`.
- For concurrent apps, wraps it into an internal request object and enqueues it in the system.
- `ConcurrentData` contains shared memory for future stages.
- Each `ConcurrentData` includes:
- Original `HttpRequest`.
- Original `HttpResponse`.
- A pendingQueries that indicates the pending queries to be processed.

=== Decomposer (Assembler)
**Role**: Split request.

**Functionality**:

- Decomposes each received request into smaller, independent processing units called `DataUnit`.
- Each `DataUnit` includes:
- A pointer to a shared `ConcurrentData`. 
- Index to store the results of the operation.

=== Calculator (Assembler)

**Role**: Operation processor.

**Functionality**:

- Takes individual `DataUnit` and performs the required computation.
- Stores the results in the corresponding result vector of the unit.
- Send the processed `DataUnit` to the `RepliesAssembler`.

=== RepliesAssembler (Assembler)

**Role**: Reassembles the initial query.

**Functionality**:

- Gathers all `DataUnit`s belonging to the same original request.
- Send completed `ConcurrentData` object to the ClientResponder.

=== ClientResponder (Consumer)

**Role**: Builds the response and sends it to the client.

**Functionality**:

- Build response with the `ConcurrentData` object and sends it back to the client.
- Delete de `ConcurrentData` object to free memory.

[[calculators_designs]]
== Calculators designs

In this section, pseudocode for the calculators' algorithms will be presented. Note that both calculators share a common isPrime procedure.

=== Prime factorization

For prime factorization, the selected approach was straightforward: divide the number by prime numbers, from 2 onwards, whilst counting the amount of times this was possible by each one. This process does not stop until the current prime number exceeds the square root of the number's current value.

Note that the processNumber procedure adds each prime factor and its exponent next to each other, continuously, inside a vector. It also returns the amount of prime factors it registered.

[#prime_fact_calc]
[source,delphi]
----
include::PrimeFactCalc.pseudo[]
----

=== Goldbach sums

Similar to the prime factorization calculator, a processNumber procedure was created for constructing responses for Goldbach Sums requests. The two conjectures were in turn divided into two methods, named after their respective conjecture.

For this version, both methods use a find-the-complement approach with for loops to find the sums of prime numbers. Sums are stored in a vector, that follow after the initial storage of the number. If the number is even, then the sums will come in pairs, if it's odd, in trios. The process number procedure also returns the amount of sums it found for the number. The pseudocode for this calculator can be found below.

[#golbach_calc]
[source,delphi]
----
include::GoldbachCalc.pseudo[]
----
== Resources
Visit https://jeisson.ecci.ucr.ac.cr/concurrente/2025a/proyectos/webserv/ for more information about the project.

Visit https://drive.google.com/file/d/16KxjAQ0D0jIqLfzJsC4BZYRnn1Ba-Wyk/view?usp=sharing for full diagram resolution.