= Design of solution
:experimental:
:nofooter:
:source-highlighter: highlightjs
:stem:
:toc:
:xrefstyle: short

[[web_server_design]]
== Web Server design

The following diagram shows the design for the concurrent web server, using two fake clients to show how requests will be responded for both Prime Factorization and Goldbach Sums web apps. Note that inheritances involving added relevant classes are attached in the surroundings of the process diagram.

[#web_server_diagram]
.Web server diagram
image::web_server_13_design.svg[algin="center"]

[[master_production_line]]
== Master production line

=== HttpConnectionHandler (Assembler)

**Role**: Initial assembler and entry point for incoming HTTP requests.

**Functionality**:

- Accepts connections from clients.
- Ask applications to parses the `HttpRequest`.
- For concurrent apps, wraps it into an internal request object and enqueues it in the system.
- `ConcurrentData` contains shared memory for future stages.
- Each `ConcurrentData` includes:
- Original `HttpRequest`.
- Original `HttpResponse`.
- A pendingQueries that indicates the pending queries to be processed.

=== Decomposer (Assembler)
**Role**: Split request.

**Functionality**:

- Decomposes each received request into smaller, independent processing units called `DataUnit`.
- Each `DataUnit` includes:
- A pointer to a shared `ConcurrentData`. 
- Index to store the results of the operation.

=== Distributor (Dispatcher)
**Role**: Distributes `DataUnit`s to the calculators or the ResponseClient.

**Functionality**:

- Determines if the are available workers to process the `DataUnit` and sends it to the ResponseClient
- If no workers are available, it sends the `DataUnit` to the calculators.

=== RequestClient (Consumer)
**Role**: Serializes the `DataUnit` and sends it to the worker server.

**Functionality**:

- Recieves `DataUnit`s from the Distributor.
- Serializes the `DataUnit` and sends it to the worker server at output buffer.

=== MasterServer (TcpServer, Producer)
**Role**: Accepts connections from clients.

**Functionality**:

- Listens for incoming worker connections.
- Accepts connections from workers and their socket to the WorkerConnectionHandlers.


=== WorkerConnectionHandler (Assembler)
**Role**: Read results from worker connections.

**Functionality**:

- Reads results from worker connections at input buffer.
- Deserializes result into a `DataUnit` and sends it to the RepliesAssembler.

=== Calculator (Assembler)

**Role**: Operation processor.

**Functionality**:

- Takes individual `DataUnit` and performs the required computation.
- Stores the results in the corresponding result vector of the unit.
- Send the processed `DataUnit` to the `RepliesAssembler`.

=== RepliesAssembler (Assembler)

**Role**: Reassembles the initial query.

**Functionality**:

- Gathers all `DataUnit`s belonging to the same original request.
- Send completed `ConcurrentData` object to the ClientResponder.

=== ClientResponder (Consumer)
**Role**: Builds the response and sends it to the client.

**Functionality**:

- Build response with the `ConcurrentData` object and sends it back to the client.
- Delete de `ConcurrentData` object to free memory.


[[worker_production_line]]
== Worker production line

=== RequestServer (Producer)

**Role**: Reads work requests

**Functionality**:

- Reads incoming requests from the master server at input buffer.
- Deserializes give query and send it to the calculators.

=== ResponseClient (TcpClient, Consumer)
**Role**: Connects to the master server, sends the results.

**Functionality**: 

- Connects to the master server given its port and IP address.
- Waits for calculated results to serialize them from a `DataUnit`.
- Sends the results to the master server at output buffer.

[[calculators_designs]]
== Calculators designs

In this section, pseudocode for the calculators' algorithms will be presented. Note that both calculators share a common isPrime procedure.

=== Prime factorization

For prime factorization, the selected approach was straightforward: divide the number by prime numbers, from 2 onwards, whilst counting the amount of times this was possible by each one. This process does not stop until the current prime number exceeds the square root of the number's current value.

Note that the processNumber procedure adds each prime factor and its exponent next to each other, continuously, inside a vector. It also returns the amount of prime factors it registered.

[#prime_fact_calc]
[source,delphi]
----
include::PrimeFactCalc.pseudo[]
----

=== Goldbach sums

Similar to the prime factorization calculator, a processNumber procedure was created for constructing responses for Goldbach Sums requests. The two conjectures were in turn divided into two methods, named after their respective conjecture.

For this version, both methods use a find-the-complement approach with for loops to find the sums of prime numbers. Sums are stored in a vector, that follow after the initial storage of the number. If the number is even, then the sums will come in pairs, if it's odd, in trios. The process number procedure also returns the amount of sums it found for the number. The pseudocode for this calculator can be found below.

[#golbach_calc]
[source,delphi]
----
include::GoldbachCalc.pseudo[]
----
== Resources
Visit https://jeisson.ecci.ucr.ac.cr/concurrente/2025a/proyectos/webserv/ for more information about the project.

Visit https://drive.google.com/file/d/1jUVtudWMtvezexsBjFGDk6oShX4G5bpa/view?usp=sharing for full diagram resolution.